# -*- coding: utf-8 -*-
"""Boooooom.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EDajwjJlcKvSQuI5uWj1cR5wIidimZ8-
"""

def boom_trach(nums):
  for num in nums:
    if num % 7 == 0 and str(num).endswith('7'):
      print('boom_trach')
    elif num % 7 == 0:
      print('boom')
    elif str(num).endswith('7'):
      print('trach')
    else:
      print(num)

up_to_hundred = list(range(1, 101))
boom_trach(up_to_hundred)