# -*- coding: utf-8 -*-
"""mini_pro.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wLoq1E0RIGNVXa2fpoJpz0byywFRV98o
"""

import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv('/content/train.csv')
df.head(5)
df.shape #9800,18
df.info()
df.columns = df.columns.str.strip().str.lower().str.replace(' ', '_')
df.columns

df['order_date'] = pd.to_datetime(df['order_date'], dayfirst =True)
df['ship_date'] = pd.to_datetime(df['ship_date'], dayfirst =True)
df['year'] = df['order_date'].dt.year
df['month'] = df['order_date'].dt.month
#df.head(5)

q1 = df.groupby(['category', 'sub-category']).agg(yearly =('year','first'), sales = ('sales','sum'))

#q2 = df.groupby('state').agg(yearly =('year','first'), sales = ('sales','sum'))
q2 = df.groupby(['state', 'year'], as_index=False).agg(sales = ('sales','sum'))
q2_matrix_df = q2.pivot(index='state', columns='year', values='sales').fillna(0)

q3 = df.loc[df['sales'].idxmax(), ['product_name', 'sales']].to_frame()
q3

df.groupby("category")["sales"].sum().plot(kind="bar", title="Sales by Category")
df.groupby("year")["sales"].sum().plot(kind="bar", title="Sales by year")
df.groupby("state")["sales"].sum().plot(kind="bar", title="Sales by state")

max_order = df.groupby('order_id', as_index=False).agg(customer_name=('customer_name', 'first'),total =('sales','sum')).sort_values('total', ascending=False).head(1)
max_order