# -*- coding: utf-8 -*-
"""NY_City_Payroll.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19_oV2TF2dLCpTeyz4gNIXAIdTSI3aQEI
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('/content/Citywide_Payroll_Data__Fiscal_Year_.csv')
df.columns
#df.info()
df.head(5)
df.columns = df.columns.str.strip().str.lower().str.replace(' ', '_')
df.columns
df['base_salary'] = df['base_salary'].str.replace('$', '').astype(float)
df['regular_gross_paid']=df['regular_gross_paid'].str.replace('$', '').astype(float)
df['total_ot_paid'] = df['total_ot_paid'].str.replace('$', '').astype(float)
df['total_other_pay'] = df['total_other_pay'].str.replace('$', '').astype(float)

df['total_paid'] =df['regular_gross_paid'] +df['total_ot_paid'] +df['total_other_pay']
#df.info()
df.head(5)

q1 = df.groupby(['fiscal_year', 'agency_name'], as_index=False).agg(n_worker = ('first_name', 'size'),t_role=('title_description','nunique') , total_paid = ('total_paid', 'sum')).sort_values('total_paid', ascending=False)
q1.head(20)

active_june_30 = df[df['leave_status_as_of_june_30'] == 'ACTIVE' ]
active_june_30
q2 = active_june_30.groupby(['fiscal_year', 'agency_name'], as_index=False).agg(n_worker = ('first_name', 'size'))
q2

Average_Base_Salary = df.groupby('agency_name', as_index=False).agg(Average_Base_Salary = ('base_salary', 'mean'))
Average_Base_Salary

y2016=df[df['fiscal_year']==2016].groupby('agency_name').agg(worker_n =('first_name', 'size'),total_payment =('total_paid','sum') )
y2016

